version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    #command: "-b /opt/irisapp/vcopy.sh"
    command: --check-caps false
    #environment:
    #  - ISC_DATA_DIRECTORY=/voldata/iconfig
    #init: true
    restart: always
    ports:
      - 19800:1972
      - 57700:52773
      - 53773
    volumes:
# no license required for community image    
#      - ~/iris.key:/usr/irissys/mgr/iris.key
      - /efs/ICS:/ICS
    #  - /efs/ICS/volumes/riches/voldata:/voldata
