version: '3.8'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    init: true
    restart: always
    ports: 
      - 32769:51773
      - 32768:52773
      - 53773
    volumes:
      - riches:/opt/irisapp/data

volumes:
  riches:
